### ISSUE TITLE
Needs auto referenced checkbox turned on in ASMDEF.

### ISSUE THREAD

**Issue by leorid** [ryanslikesocool/EaseKit#6]
When "Auto Referenced" Checkbox is turned off in the ASMDEF, it won't be included as reference in the Assembly-CSharp assembly. This leads to compile errors like 
`The type or namespace name 'Easings' could not be found (are you missing a using directive or an assembly reference?)` .

**Comment by ryanslikesocool** [comment]
Fixed in v1.3.2.  Sorry I missed this comment!  I normally manually include it in each project's asmdefs and didn't think that people wouldn't be using them.  Thanks for pointing this out.
